// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/richer/q-workflow/infra/mysql/model"
)

func newHelloWorld(db *gorm.DB, opts ...gen.DOOption) helloWorld {
	_helloWorld := helloWorld{}

	_helloWorld.helloWorldDo.UseDB(db, opts...)
	_helloWorld.helloWorldDo.UseModel(&model.HelloWorld{})

	tableName := _helloWorld.helloWorldDo.TableName()
	_helloWorld.ALL = field.NewAsterisk(tableName)
	_helloWorld.ID = field.NewUint(tableName, "id")
	_helloWorld.CreatedAt = field.NewTime(tableName, "created_at")
	_helloWorld.UpdatedAt = field.NewTime(tableName, "updated_at")
	_helloWorld.Title = field.NewString(tableName, "title")
	_helloWorld.Description = field.NewString(tableName, "description")

	_helloWorld.fillFieldMap()

	return _helloWorld
}

type helloWorld struct {
	helloWorldDo helloWorldDo

	ALL         field.Asterisk
	ID          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	Title       field.String
	Description field.String

	fieldMap map[string]field.Expr
}

func (h helloWorld) Table(newTableName string) *helloWorld {
	h.helloWorldDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h helloWorld) As(alias string) *helloWorld {
	h.helloWorldDo.DO = *(h.helloWorldDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *helloWorld) updateTableName(table string) *helloWorld {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewUint(table, "id")
	h.CreatedAt = field.NewTime(table, "created_at")
	h.UpdatedAt = field.NewTime(table, "updated_at")
	h.Title = field.NewString(table, "title")
	h.Description = field.NewString(table, "description")

	h.fillFieldMap()

	return h
}

func (h *helloWorld) WithContext(ctx context.Context) *helloWorldDo {
	return h.helloWorldDo.WithContext(ctx)
}

func (h helloWorld) TableName() string { return h.helloWorldDo.TableName() }

func (h helloWorld) Alias() string { return h.helloWorldDo.Alias() }

func (h helloWorld) Columns(cols ...field.Expr) gen.Columns { return h.helloWorldDo.Columns(cols...) }

func (h *helloWorld) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *helloWorld) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 5)
	h.fieldMap["id"] = h.ID
	h.fieldMap["created_at"] = h.CreatedAt
	h.fieldMap["updated_at"] = h.UpdatedAt
	h.fieldMap["title"] = h.Title
	h.fieldMap["description"] = h.Description
}

func (h helloWorld) clone(db *gorm.DB) helloWorld {
	h.helloWorldDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h helloWorld) replaceDB(db *gorm.DB) helloWorld {
	h.helloWorldDo.ReplaceDB(db)
	return h
}

type helloWorldDo struct{ gen.DO }

func (h helloWorldDo) Debug() *helloWorldDo {
	return h.withDO(h.DO.Debug())
}

func (h helloWorldDo) WithContext(ctx context.Context) *helloWorldDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h helloWorldDo) ReadDB() *helloWorldDo {
	return h.Clauses(dbresolver.Read)
}

func (h helloWorldDo) WriteDB() *helloWorldDo {
	return h.Clauses(dbresolver.Write)
}

func (h helloWorldDo) Session(config *gorm.Session) *helloWorldDo {
	return h.withDO(h.DO.Session(config))
}

func (h helloWorldDo) Clauses(conds ...clause.Expression) *helloWorldDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h helloWorldDo) Returning(value interface{}, columns ...string) *helloWorldDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h helloWorldDo) Not(conds ...gen.Condition) *helloWorldDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h helloWorldDo) Or(conds ...gen.Condition) *helloWorldDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h helloWorldDo) Select(conds ...field.Expr) *helloWorldDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h helloWorldDo) Where(conds ...gen.Condition) *helloWorldDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h helloWorldDo) Order(conds ...field.Expr) *helloWorldDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h helloWorldDo) Distinct(cols ...field.Expr) *helloWorldDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h helloWorldDo) Omit(cols ...field.Expr) *helloWorldDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h helloWorldDo) Join(table schema.Tabler, on ...field.Expr) *helloWorldDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h helloWorldDo) LeftJoin(table schema.Tabler, on ...field.Expr) *helloWorldDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h helloWorldDo) RightJoin(table schema.Tabler, on ...field.Expr) *helloWorldDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h helloWorldDo) Group(cols ...field.Expr) *helloWorldDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h helloWorldDo) Having(conds ...gen.Condition) *helloWorldDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h helloWorldDo) Limit(limit int) *helloWorldDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h helloWorldDo) Offset(offset int) *helloWorldDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h helloWorldDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *helloWorldDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h helloWorldDo) Unscoped() *helloWorldDo {
	return h.withDO(h.DO.Unscoped())
}

func (h helloWorldDo) Create(values ...*model.HelloWorld) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h helloWorldDo) CreateInBatches(values []*model.HelloWorld, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h helloWorldDo) Save(values ...*model.HelloWorld) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h helloWorldDo) First() (*model.HelloWorld, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HelloWorld), nil
	}
}

func (h helloWorldDo) Take() (*model.HelloWorld, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HelloWorld), nil
	}
}

func (h helloWorldDo) Last() (*model.HelloWorld, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HelloWorld), nil
	}
}

func (h helloWorldDo) Find() ([]*model.HelloWorld, error) {
	result, err := h.DO.Find()
	return result.([]*model.HelloWorld), err
}

func (h helloWorldDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HelloWorld, err error) {
	buf := make([]*model.HelloWorld, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h helloWorldDo) FindInBatches(result *[]*model.HelloWorld, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h helloWorldDo) Attrs(attrs ...field.AssignExpr) *helloWorldDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h helloWorldDo) Assign(attrs ...field.AssignExpr) *helloWorldDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h helloWorldDo) Joins(fields ...field.RelationField) *helloWorldDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h helloWorldDo) Preload(fields ...field.RelationField) *helloWorldDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h helloWorldDo) FirstOrInit() (*model.HelloWorld, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HelloWorld), nil
	}
}

func (h helloWorldDo) FirstOrCreate() (*model.HelloWorld, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HelloWorld), nil
	}
}

func (h helloWorldDo) FindByPage(offset int, limit int) (result []*model.HelloWorld, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h helloWorldDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h helloWorldDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h helloWorldDo) Delete(models ...*model.HelloWorld) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *helloWorldDo) withDO(do gen.Dao) *helloWorldDo {
	h.DO = *do.(*gen.DO)
	return h
}
